# Generated by Django 6.0.5 on 2026-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('obra', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto/Obra',
                'verbose_name_plural': 'Proyectos/Obras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='ParteTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('jornada', models.CharField(choices=[('normal', 'Normal - 1h comida'), ('intensiva', 'Intensiva')], max_length=20)),
                ('conductor', models.BooleanField(default=False)),
                ('entrada_obra', models.TimeField(blank=True, null=True)),
                ('salida_obra', models.TimeField(blank=True, null=True)),
                ('hora_comida', models.TimeField(blank=True, null=True)),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.CharField(max_length=200)),
                ('obra', models.CharField(max_length=250)),
                ('trabajos', models.TextField()),
                ('admin', models.TextField(blank=True)),
                ('materiales', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='partes/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partes.proyecto')),
                ('companero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partes_como_companero', to='partes.tecnico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='partes.tecnico')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partes.vehiculo')),
            ],
            options={
                'verbose_name': 'Parte de trabajo',
                'verbose_name_plural': 'Partes de trabajo',
                'ordering': ['-created_at'],
            },
        ),
    ]
