# Generated by Django 6.0.5 on 2026-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['orden', 'codigo'], 'verbose_name': 'Proyecto/Obra', 'verbose_name_plural': 'Proyectos/Obras'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Trabajador / Técnico', 'verbose_name_plural': 'Trabajadores / Técnicos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['orden', 'matricula'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='cliente_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='companero_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='partes_csv/'),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='google_sheets_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='google_sheets_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='id_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='materiales_instalados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='obra_snapshot',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='tecnico_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='tecnico_nombre_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='trabajos_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='trabajos_realizados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='puede_ser_companero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='puede_ser_tecnico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partetrabajo',
            name='cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='partetrabajo',
            name='obra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='partetrabajo',
            name='trabajos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
