# Generated by Django 6.0.5 on 2026-05-31 12:17

import django.db.models.deletion
import partes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0002_alter_proyecto_options_alter_tecnico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteTrabajoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partes.models.parte_photo_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='partes.partetrabajo')),
            ],
            options={
                'verbose_name': 'Foto de parte',
                'verbose_name_plural': 'Fotos de partes',
                'ordering': ['created_at'],
            },
        ),
    ]
