# Generated by Django 6.0.5 on 2026-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0003_partetrabajofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
