# Generated by Django 6.0.5 on 2026-06-18 09:40

import django.db.models.deletion
import workdocs.models
from django.conf import settings
from django.db import migrations, models


def create_existing_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model('workdocs', 'UserProfile')
    for user in User.objects.all():
        role = 'admin' if user.is_superuser else 'technician'
        UserProfile.objects.get_or_create(user=user, defaults={'role': role})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('NUEVA', 'Nueva'), ('ASIGNADA', 'Asignada'), ('EN_CAMINO', 'En camino'), ('EN_OBJETO', 'En objeto'), ('EN_PROCESO', 'En proceso'), ('PENDIENTE_REVISION', 'Pendiente revisión'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='NUEVA', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creada'), ('assigned', 'Asignada'), ('status', 'Estado'), ('file', 'Archivo'), ('comment', 'Comentario'), ('audio', 'Audio')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workdocs.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de tarea',
                'verbose_name_plural': 'Eventos de tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workdocs.models.task_file_upload_to)),
                ('file_type', models.CharField(choices=[('photo', 'Foto'), ('pdf', 'PDF'), ('video', 'Vídeo'), ('document', 'Documento'), ('audio', 'Audio'), ('other', 'Otro')], default='other', max_length=20)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workdocs.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_task_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de tarea',
                'verbose_name_plural': 'Archivos de tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskVoiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=workdocs.models.voice_report_upload_to)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Hecho'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_reports', to='workdocs.task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe de voz',
                'verbose_name_plural': 'Informes de voz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('technician', 'Technician')], default='technician', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de trabajo',
                'verbose_name_plural': 'Perfiles de trabajo',
            },
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
