# Generated by Django 6.0.5 on 2026-06-18 12:15

from django.conf import settings
from django.db import migrations, models


def copy_primary_technician(apps, schema_editor):
    Task = apps.get_model('workdocs', 'Task')
    for task in Task.objects.exclude(assigned_to__isnull=True):
        task.technicians.add(task.assigned_to_id)


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0002_userprofile_active_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='technicians',
            field=models.ManyToManyField(blank=True, limit_choices_to={'work_profile__role': 'technician'}, related_name='technician_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_primary_technician, migrations.RunPython.noop),
    ]
