# Generated by Django 6.0.5 on 2026-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0003_task_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskvoicereport',
            name='transcript_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Transcribiendo'), ('done', 'Hecho'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
