# Generated by Django 6.0.5 on 2026-06-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_vehiculo_image'),
        ('workdocs', '0004_alter_taskvoicereport_transcript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partes.vehiculo'),
        ),
    ]
