# Generated by Django 6.0.5 on 2026-06-18 18:00

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_description_reports(apps, schema_editor):
    TaskEvent = apps.get_model('workdocs', 'TaskEvent')
    Task = apps.get_model('workdocs', 'Task')
    TaskVoiceReport = apps.get_model('workdocs', 'TaskVoiceReport')
    description_events = TaskEvent.objects.filter(
        event_type='audio',
        comment__startswith='Descripción de voz',
    ).order_by('created_at')
    for event in description_events:
        reports = TaskVoiceReport.objects.filter(
            task_id=event.task_id,
            technician_id=event.user_id,
            report_type='report',
        )
        best_report = None
        best_delta = None
        for report in reports:
            delta = abs((report.created_at - event.created_at).total_seconds())
            if best_delta is None or delta < best_delta:
                best_report = report
                best_delta = delta
        if best_report and best_delta is not None and best_delta <= 30:
            best_report.report_type = 'description'
            best_report.save(update_fields=['report_type'])
            if best_report.transcript_status == 'done' and best_report.transcript_text:
                task = Task.objects.get(pk=best_report.task_id)
                marker = f'Transcripción de descripción #{best_report.pk}:'
                if marker not in task.description:
                    prefix = '\n\n' if task.description.strip() else ''
                    task.description = f'{task.description}{prefix}{marker}\n{best_report.transcript_text}'
                    task.save(update_fields=['description', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0005_task_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continued_tasks', to='workdocs.task'),
        ),
        migrations.AddField(
            model_name='taskvoicereport',
            name='report_type',
            field=models.CharField(choices=[('report', 'Informe'), ('description', 'Descripción')], default='report', max_length=20),
        ),
        migrations.RunPython(mark_existing_description_reports, migrations.RunPython.noop),
    ]
