# Generated by Django 6.0.5 on 2026-06-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0006_task_parent_task_taskvoicereport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='workdocs.taskevent'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
