# Generated by Django 6.0.5 on 2026-06-18 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0007_taskevent_parent_event_taskevent_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEventRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='workdocs.taskevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_task_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de evento',
                'verbose_name_plural': 'Lecturas de eventos',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
