# Generated by Django 6.0.5 on 2026-06-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0008_taskeventread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('uds', 'uds'), ('m', 'm'), ('m²', 'm²'), ('kg', 'kg'), ('l', 'l'), ('rollos', 'rollos'), ('cajas', 'cajas'), ('otros', 'otros')], default='uds', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_gathered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_task_materials', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_uses', to='workdocs.material')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workdocs.task')),
            ],
            options={
                'verbose_name': 'Material de tarea',
                'verbose_name_plural': 'Materiales de tarea',
                'ordering': ['material__name'],
                'unique_together': {('task', 'material')},
            },
        ),
    ]
