# Generated by Django 6.0.5 on 2026-06-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdocs', '0013_taskworkerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='flagged_for_admin',
            field=models.BooleanField(default=False),
        ),
    ]
