from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='workdocs_dashboard'),
    path('api/users/search/', views.user_search, name='workdocs_user_search'),
    path('api/vehicles/search/', views.vehicle_search, name='workdocs_vehicle_search'),
    path('api/materiales/buscar/', views.material_search, name='workdocs_material_search'),
    path('tareas/<int:pk>/materiales/', views.task_materials, name='workdocs_task_materials'),
    path('tareas/<int:pk>/materiales/<int:mat_pk>/', views.task_material_update, name='workdocs_task_material_update'),
    path('tareas/', views.task_list, name='workdocs_task_list'),
    path('tareas/nueva/', views.task_create, name='workdocs_task_create'),
    path('tareas/<int:pk>/', views.task_detail, name='workdocs_task_detail'),
    path('tareas/<int:pk>/comentarios/<int:event_pk>/reaccion/', views.task_comment_reaction, name='workdocs_task_comment_reaction'),
    path('tareas/<int:pk>/comentarios/<int:event_pk>/eliminar/', views.task_comment_delete, name='workdocs_task_comment_delete'),
    path('tareas/<int:pk>/archivos/<int:file_pk>/eliminar/', views.task_file_delete, name='workdocs_task_file_delete'),
    path('tareas/<int:pk>/continuar/', views.task_continue, name='workdocs_task_continue'),
    path('tareas/<int:pk>/quick-status/', views.task_quick_status, name='workdocs_task_quick_status'),
    path('tareas/<int:pk>/estado/<slug:action>/', views.technician_status, name='workdocs_technician_status'),
    path('tareas/<int:pk>/informe/', views.task_worker_report, name='workdocs_task_worker_report'),
    path('tareas/<int:pk>/pdf/', views.task_pdf, name='workdocs_task_pdf'),
    path('tareas/<int:pk>/vehiculo/', views.task_set_vehicle, name='workdocs_task_set_vehicle'),
    path('tareas/<int:pk>/equipo/', views.task_toggle_technician, name='workdocs_task_toggle_technician'),
    path('api/transcribir/', views.transcribe_audio_inline, name='workdocs_transcribe_inline'),
    path('instrucciones/', views.worker_instructions, name='workdocs_worker_instructions'),
    path('tecnicos/<int:pk>/', views.technician_detail, name='workdocs_technician_detail'),
    path('perfil/', views.profile, name='workdocs_profile'),
    path('usuarios/', views.user_list, name='workdocs_users'),
    path('usuarios/<int:pk>/editar/', views.user_edit, name='workdocs_user_edit'),
    path('usuarios/<int:pk>/toggle-active/', views.user_toggle_active, name='workdocs_user_toggle_active'),
    path('usuarios/<int:pk>/tareas/', views.user_tasks, name='workdocs_user_tasks'),
    path('vehiculos/', views.vehicles, name='workdocs_vehicles'),
    path('vehiculos/<int:pk>/', views.vehicles, name='workdocs_vehicle_edit'),
]
